### ISSUE TITLE
update links in project description

### ISSUE THREAD

**Issue by katlund** [mathworks/matlab-engine-for-python#39]
On the main [project description page](https://pypi.org/project/matlabengine/), the link for supported python versions by MATLAB release is dead: https://www.mathworks.com/content/dam/mathworks/mathworks-dot-com/support/sysreq/files/python-compatibility.pdf

I think this is the correct link: https://mathworks.com/support/requirements/python-compatibility.html

Also, there used to be a page stating which version of `matlabengine` works for which version of MATLAB; I can't find this anywhere now.  It would be helpful to have that in the docs too.  At the moment, I have to click around the [releases page](https://github.com/mathworks/matlab-engine-for-python/releases) one-by-one.

I'm relying heavily on this tool for my own work and need to be able to point potential users to the right version of `matlabengine` for their setup.

**Comment by alanfmw** [comment]
Many thanks for reporting the broken link! It has now been fixed in all branches.

As for the list of versions of `matlabengine` corresponding to versions of MATLAB, you can find that in the code, in setup.py. In the most recent version, it starts at line 31:

```
    VER_TO_REL = {
        "9.9": "R2020b",
        "9.10": "R2021a",
        "9.11": "R2021b",
        "9.12": "R2022a",
        "9.13": "R2022b",
        "9.14": "R2023a",
        "23.2": "R2023b"
    }
```
As you can see from the last item in that list, the release number going forward corresponds to the last two digits of the MATLAB release identifier, plus a period, plus "1" for "a" or "2" for "b". This should be much easier to remember than the older release numbers.
